DROP TABLE IF EXISTS SECTOR CASCADE;
DROP TABLE IF EXISTS ANIMAL CASCADE;

CREATE TABLE SECTOR (
 SECTOR_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(50) NOT NULL,
 ANIMALS BIGINT
);

CREATE TABLE ANIMAL(
 ANIMAL_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(50) NOT NULL,
 KARMA_UNITS INT,
 TYPE VARCHAR(50),
 SECTOR_ID BIGINT,
 FOREIGN KEY (SECTOR_ID) REFERENCES SECTOR(SECTOR_ID)
);

ALTER TABLE SECTOR
ADD FOREIGN KEY (ANIMALS) REFERENCES ANIMAL(ANIMAL_ID);

INSERT INTO SECTOR(NAME, ANIMALS) VALUES('sahara', NULL);
INSERT INTO SECTOR(NAME, ANIMALS) VALUES('tundra', NULL);

INSERT INTO ANIMAL(NAME, KARMA_UNITS, TYPE, SECTOR_ID) VALUES ('mietek', 11, 'LION', 1);
INSERT INTO ANIMAL(NAME, KARMA_UNITS, TYPE, SECTOR_ID) VALUES ('wici', 4, 'RABBIT', 1);
INSERT INTO ANIMAL(NAME, KARMA_UNITS, TYPE, SECTOR_ID) VALUES ('kici', 20, 'ELEPHANT', 1);
INSERT INTO ANIMAL(NAME, KARMA_UNITS, TYPE, SECTOR_ID) VALUES ('drem', 20, 'RABBIT', 2);
